In [1]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("Student_Performance_Dataset.csv")

# Display dataset
display(df)

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
0,S0001,15,Male,12,1.0,65,Postgraduate,No,No,40,39,72,81,50.33,Average,Pass
1,S0002,19,Female,9,1.6,58,Graduate,No,Yes,80,44,35,47,53.00,Average,Pass
2,S0003,14,Female,12,3.6,64,High School,Yes,Yes,83,73,59,58,71.67,Good,Pass
3,S0004,18,Female,9,5.5,68,Postgraduate,Yes,No,68,48,77,54,64.33,Average,Pass
4,S0005,14,Male,10,5.0,80,High School,Yes,No,41,46,36,68,41.00,Poor,Fail
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,S4996,17,Male,11,4.0,50,Graduate,No,No,64,60,70,93,64.67,Average,Pass
4996,S4997,19,Male,10,5.6,90,High School,Yes,No,44,59,43,63,48.67,Poor,Fail
4997,S4998,16,Female,9,2.3,61,Graduate,No,No,95,41,82,62,72.67,Good,Pass
4998,S4999,15,Male,11,2.9,82,Graduate,No,Yes,66,45,61,75,57.33,Average,Pass
4999,S5000,19,Female,10,2.0,97,Postgraduate,No,Yes,69,53,87,77,69.67,Good,Pass

In [2]:
print("Pandas version:", pd.__version__)
print("Built on top of NumPy version:", np.__version__)

Pandas version: 3.0.3
Built on top of NumPy version: 2.5.1

In [3]:
s = pd.Series([80, 75, 90, 85], index=["A", "B", "C", "D"], name="Marks")

print(s)
print("\nType:", type(s))
print("Value at label 'B':", s["B"])

A    80
B    75
C    90
D    85
Name: Marks, dtype: int64

Type: <class 'pandas.Series'>
Value at label 'B': 75

In [4]:
print("Type:", type(df))
print("Columns:", list(df.columns))
print("Index:", df.index.tolist())

display(df)

Type: <class 'pandas.DataFrame'>
Columns: ['Student_ID', 'Age', 'Gender', 'Class', 'Study_Hours_Per_Day', 'Attendance_Percentage', 'Parental_Education', 'Internet_Access', 'Extracurricular_Activities', 'Math_Score', 'Science_Score', 'English_Score', 'Previous_Year_Score', 'Final_Percentage', 'Performance_Level', 'Pass_Fail']

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
0,S0001,15,Male,12,1.0,65,Postgraduate,No,No,40,39,72,81,50.33,Average,Pass
1,S0002,19,Female,9,1.6,58,Graduate,No,Yes,80,44,35,47,53.00,Average,Pass
2,S0003,14,Female,12,3.6,64,High School,Yes,Yes,83,73,59,58,71.67,Good,Pass
3,S0004,18,Female,9,5.5,68,Postgraduate,Yes,No,68,48,77,54,64.33,Average,Pass
4,S0005,14,Male,10,5.0,80,High School,Yes,No,41,46,36,68,41.00,Poor,Fail
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,S4996,17,Male,11,4.0,50,Graduate,No,No,64,60,70,93,64.67,Average,Pass
4996,S4997,19,Male,10,5.6,90,High School,Yes,No,44,59,43,63,48.67,Poor,Fail
4997,S4998,16,Female,9,2.3,61,Graduate,No,No,95,41,82,62,72.67,Good,Pass
4998,S4999,15,Male,11,2.9,82,Graduate,No,Yes,66,45,61,75,57.33,Average,Pass
4999,S5000,19,Female,10,2.0,97,Postgraduate,No,Yes,69,53,87,77,69.67,Good,Pass

In [5]:
df.to_csv("students.csv", index=False)
df_from_csv = pd.read_csv("students.csv")

df.to_json("students.json", orient="records")
df_from_json = pd.read_json("students.json")

display(df_from_csv.tail())

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
4995,S4996,17,Male,11,4.0,50,Graduate,No,No,64,60,70,93,64.67,Average,Pass
4996,S4997,19,Male,10,5.6,90,High School,Yes,No,44,59,43,63,48.67,Poor,Fail
4997,S4998,16,Female,9,2.3,61,Graduate,No,No,95,41,82,62,72.67,Good,Pass
4998,S4999,15,Male,11,2.9,82,Graduate,No,Yes,66,45,61,75,57.33,Average,Pass
4999,S5000,19,Female,10,2.0,97,Postgraduate,No,Yes,69,53,87,77,69.67,Good,Pass

In [6]:
print("First 3 rows:")
display(df.head(3))

print("Last 3 rows:")
display(df.tail(3))

print("Info:")
df.info()

print("Describe:")
display(df.describe())

print("Shape:", df.shape)

First 3 rows:

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
0,S0001,15,Male,12,1.0,65,Postgraduate,No,No,40,39,72,81,50.33,Average,Pass
1,S0002,19,Female,9,1.6,58,Graduate,No,Yes,80,44,35,47,53.00,Average,Pass
2,S0003,14,Female,12,3.6,64,High School,Yes,Yes,83,73,59,58,71.67,Good,Pass

Last 3 rows:

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
4997,S4998,16,Female,9,2.3,61,Graduate,No,No,95,41,82,62,72.67,Good,Pass
4998,S4999,15,Male,11,2.9,82,Graduate,No,Yes,66,45,61,75,57.33,Average,Pass
4999,S5000,19,Female,10,2.0,97,Postgraduate,No,Yes,69,53,87,77,69.67,Good,Pass

Info:
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  5000 non-null   str
 1   Age                         5000 non-null   int64
 2   Gender                      5000 non-null   str
 3   Class                       5000 non-null   int64
 4   Study_Hours_Per_Day         5000 non-null   float64
 5   Attendance_Percentage       5000 non-null   int64
 6   Parental_Education          5000 non-null   str
 7   Internet_Access             5000 non-null   str
 8   Extracurricular_Activities  5000 non-null   str
 9   Math_Score                  5000 non-null   int64
 10  Science_Score               5000 non-null   int64
 11  English_Score               5000 non-null   int64
 12  Previous_Year_Score         5000 non-null   int64
 13  Final_Percentage            5000 non-null   float64
 14  Performance_Level           5000 non-null   str
 15  Pass_Fail                   5000 non-null   str
dtypes: float64(2), int64(7), str(7)
memory usage: 625.1 KB
Describe:

,Age,Class,Study_Hours_Per_Day,Attendance_Percentage,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,16.508800,10.496400,3.287260,74.919800,67.754800,66.895400,67.782800,67.282200,67.477656
std,1.718637,1.106812,1.587979,14.673842,18.724487,19.141195,19.248473,16.157511,10.964081
min,14.000000,9.000000,0.500000,50.000000,35.000000,35.000000,35.000000,40.000000,36.330000
25%,15.000000,10.000000,1.900000,62.000000,52.000000,50.000000,51.000000,53.000000,59.670000
50%,17.000000,10.000000,3.300000,75.000000,68.000000,67.000000,68.000000,67.000000,67.330000
75%,18.000000,11.000000,4.700000,88.000000,84.000000,83.000000,85.000000,81.000000,75.330000
max,19.000000,12.000000,6.000000,100.000000,100.000000,100.000000,100.000000,95.000000,98.330000

Shape: (5000, 16)

In [7]:
print("loc example:")
display(df.loc[0:2, ["Student_ID", "Gender", "Final_Percentage"]])

print("iloc example:")
display(df.iloc[0:3, 0:4])

print("Students who Passed:")
display(df[df["Pass_Fail"] == "Pass"])

loc example:

  Student_ID  Gender  Final_Percentage
0      S0001    Male             50.33
1      S0002  Female             53.00
2      S0003  Female             71.67

iloc example:

  Student_ID  Age  Gender  Class
0      S0001   15    Male     12
1      S0002   19  Female      9
2      S0003   14  Female     12

Students who Passed:

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
0,S0001,15,Male,12,1.0,65,Postgraduate,No,No,40,39,72,81,50.33,Average,Pass
1,S0002,19,Female,9,1.6,58,Graduate,No,Yes,80,44,35,47,53.00,Average,Pass
2,S0003,14,Female,12,3.6,64,High School,Yes,Yes,83,73,59,58,71.67,Good,Pass
3,S0004,18,Female,9,5.5,68,Postgraduate,Yes,No,68,48,77,54,64.33,Average,Pass
5,S0006,19,Male,12,5.2,82,High School,No,Yes,88,70,46,60,68.00,Good,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4994,S4995,15,Male,9,4.0,60,High School,Yes,No,49,97,36,53,60.67,Average,Pass
4995,S4996,17,Male,11,4.0,50,Graduate,No,No,64,60,70,93,64.67,Average,Pass
4997,S4998,16,Female,9,2.3,61,Graduate,No,No,95,41,82,62,72.67,Good,Pass
4998,S4999,15,Male,11,2.9,82,Graduate,No,Yes,66,45,61,75,57.33,Average,Pass
4999,S5000,19,Female,10,2.0,97,Postgraduate,No,Yes,69,53,87,77,69.67,Good,Pass

In [8]:
print("Average Final Percentage by Gender:")
display(df.groupby("Gender")["Final_Percentage"].mean())

Average Final Percentage by Gender:

Gender
Female    67.419890
Male      67.537924
Name: Final_Percentage, dtype: float64

In [9]:
print("Average Math Score by Performance Level:")
display(df.groupby("Performance_Level")["Math_Score"].mean())

Average Math Score by Performance Level:

Performance_Level
Average      59.705792
Excellent    84.994941
Good         72.869466
Poor         46.147170
Name: Math_Score, dtype: float64

In [10]:
display(df.groupby("Gender").agg(
    Avg_Final=("Final_Percentage", "mean"),
    Avg_Math=("Math_Score", "mean"),
    Student_Count=("Student_ID", "count")
))

        Avg_Final   Avg_Math  Student_Count
Gender
Female  67.419890  67.784567           2553
Male    67.537924  67.723743           2447

In [11]:
pivot = pd.pivot_table(
    df,
    values="Final_Percentage",
    index="Gender",
    columns="Performance_Level",
    aggfunc="mean",
    fill_value=0
)

display(pivot)

Performance_Level    Average  Excellent       Good       Poor
Gender
Female             59.228601  85.480334  72.677213  45.813507
Male               58.990406  85.684422  72.646077  45.537557

In [12]:
print("Missing values:")
display(df.isnull().sum())

print("Rows containing missing values:")
display(df[df.isnull().any(axis=1)])

print("Drop missing values:")
display(df.dropna())

Missing values:

Student_ID                    0
Age                           0
Gender                        0
Class                         0
Study_Hours_Per_Day           0
Attendance_Percentage         0
Parental_Education            0
Internet_Access               0
Extracurricular_Activities    0
Math_Score                    0
Science_Score                 0
English_Score                 0
Previous_Year_Score           0
Final_Percentage              0
Performance_Level             0
Pass_Fail                     0
dtype: int64

Rows containing missing values:

Empty DataFrame
Columns: [Student_ID, Age, Gender, Class, Study_Hours_Per_Day, Attendance_Percentage, Parental_Education, Internet_Access, Extracurricular_Activities, Math_Score, Science_Score, English_Score, Previous_Year_Score, Final_Percentage, Performance_Level, Pass_Fail]
Index: []

Drop missing values:

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
0,S0001,15,Male,12,1.0,65,Postgraduate,No,No,40,39,72,81,50.33,Average,Pass
1,S0002,19,Female,9,1.6,58,Graduate,No,Yes,80,44,35,47,53.00,Average,Pass
2,S0003,14,Female,12,3.6,64,High School,Yes,Yes,83,73,59,58,71.67,Good,Pass
3,S0004,18,Female,9,5.5,68,Postgraduate,Yes,No,68,48,77,54,64.33,Average,Pass
4,S0005,14,Male,10,5.0,80,High School,Yes,No,41,46,36,68,41.00,Poor,Fail
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,S4996,17,Male,11,4.0,50,Graduate,No,No,64,60,70,93,64.67,Average,Pass
4996,S4997,19,Male,10,5.6,90,High School,Yes,No,44,59,43,63,48.67,Poor,Fail
4997,S4998,16,Female,9,2.3,61,Graduate,No,No,95,41,82,62,72.67,Good,Pass
4998,S4999,15,Male,11,2.9,82,Graduate,No,Yes,66,45,61,75,57.33,Average,Pass
4999,S5000,19,Female,10,2.0,97,Postgraduate,No,Yes,69,53,87,77,69.67,Good,Pass

In [15]:
df_filled = df.copy()

df_filled["Study_Hours_Per_Day"] = df_filled["Study_Hours_Per_Day"].fillna(
    df_filled["Study_Hours_Per_Day"].mean()
)

display(df_filled.head())

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
0,S0001,15,Male,12,1.0,65,Postgraduate,No,No,40,39,72,81,50.33,Average,Pass
1,S0002,19,Female,9,1.6,58,Graduate,No,Yes,80,44,35,47,53.00,Average,Pass
2,S0003,14,Female,12,3.6,64,High School,Yes,Yes,83,73,59,58,71.67,Good,Pass
3,S0004,18,Female,9,5.5,68,Postgraduate,Yes,No,68,48,77,54,64.33,Average,Pass
4,S0005,14,Male,10,5.0,80,High School,Yes,No,41,46,36,68,41.00,Poor,Fail

In [16]:
df_t = df_filled.copy()

# Total Marks
df_t["Total_Marks"] = df_t.apply(
    lambda row: row["Math_Score"] + row["Science_Score"] + row["English_Score"],
    axis=1
)

# Map Gender
gender_code = {
    "Male": "M",
    "Female": "F"
}

df_t["Gender_Code"] = df_t["Gender"].map(gender_code)

# Change datatype
df_t["Age"] = df_t["Age"].astype(int)

# Rename column
df_t = df_t.rename(columns={"Final_Percentage": "Final_Result"})

# Sort by Final Result
df_t = df_t.sort_values(by="Final_Result", ascending=False)

display(df_t)

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Result,Performance_Level,Pass_Fail,Total_Marks,Gender_Code
21,S0022,15,Male,12,2.8,83,Postgraduate,No,Yes,100,96,99,86,98.33,Excellent,Pass,295,M
3636,S3637,15,Female,9,3.8,90,High School,No,Yes,99,95,99,73,97.67,Excellent,Pass,293,F
3748,S3749,17,Male,11,0.5,60,Graduate,No,Yes,99,93,100,58,97.33,Excellent,Pass,292,M
2211,S2212,19,Male,11,1.8,87,Graduate,No,Yes,98,98,96,54,97.33,Excellent,Pass,292,M
1599,S1600,14,Male,9,5.0,83,High School,Yes,No,100,99,92,71,97.00,Excellent,Pass,291,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1684,S1685,14,Female,10,1.0,88,Graduate,No,Yes,39,36,40,46,38.33,Poor,Fail,115,F
1686,S1687,15,Female,11,5.4,82,Graduate,Yes,No,35,42,36,44,37.67,Poor,Fail,113,F
2157,S2158,16,Female,9,5.2,70,Postgraduate,No,Yes,35,35,43,69,37.67,Poor,Fail,113,F
3190,S3191,15,Male,9,5.0,91,Graduate,No,Yes,40,37,36,41,37.67,Poor,Fail,113,M
2718,S2719,16,Male,11,5.1,50,Postgraduate,Yes,No,36,36,37,60,36.33,Poor,Fail,109,M

In [22]:
extra_info = pd.DataFrame({
    "Student_ID": ["S0001","S0002","S0003","S0004","S0005"],
    "City": ["Pune","Mumbai","Nashik","Nagpur","Aurangabad"],
    "Scholarship": ["Yes","No","Yes","No","Yes"]
})

In [21]:
merged_df = pd.merge(df, extra_info, on="Student_ID", how="left")

print("Merge Result:")
display(merged_df.head())

Merge Result:

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail,City,Scholarship
0,S0001,15,Male,12,1.0,65,Postgraduate,No,No,40,39,72,81,50.33,Average,Pass,Pune,Yes
1,S0002,19,Female,9,1.6,58,Graduate,No,Yes,80,44,35,47,53.00,Average,Pass,Mumbai,No
2,S0003,14,Female,12,3.6,64,High School,Yes,Yes,83,73,59,58,71.67,Good,Pass,Nashik,Yes
3,S0004,18,Female,9,5.5,68,Postgraduate,Yes,No,68,48,77,54,64.33,Average,Pass,Nagpur,No
4,S0005,14,Male,10,5.0,80,High School,Yes,No,41,46,36,68,41.00,Poor,Fail,Aurangabad,Yes

In [19]:
joined_df = df.set_index("Student_ID").join(
    extra_info.set_index("Student_ID"),
    how="left"
)

print("Join Result:")
display(joined_df.head())

Join Result:

,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail,City,Scholarship
Student_ID,,,,,,,,,,,,,,,,,
S0001,15,Male,12,1.0,65,Postgraduate,No,No,40,39,72,81,50.33,Average,Pass,Pune,Yes
S0002,19,Female,9,1.6,58,Graduate,No,Yes,80,44,35,47,53.00,Average,Pass,Mumbai,No
S0003,14,Female,12,3.6,64,High School,Yes,Yes,83,73,59,58,71.67,Good,Pass,Nashik,Yes
S0004,18,Female,9,5.5,68,Postgraduate,Yes,No,68,48,77,54,64.33,Average,Pass,Nagpur,No
S0005,14,Male,10,5.0,80,High School,Yes,No,41,46,36,68,41.00,Poor,Fail,Aurangabad,Yes

In [20]:
batch1 = df.iloc[:50]
batch2 = df.iloc[50:]

concatenated_df = pd.concat([batch1, batch2], ignore_index=True)

print("Concat Result:")
display(concatenated_df)

Concat Result:

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
0,S0001,15,Male,12,1.0,65,Postgraduate,No,No,40,39,72,81,50.33,Average,Pass
1,S0002,19,Female,9,1.6,58,Graduate,No,Yes,80,44,35,47,53.00,Average,Pass
2,S0003,14,Female,12,3.6,64,High School,Yes,Yes,83,73,59,58,71.67,Good,Pass
3,S0004,18,Female,9,5.5,68,Postgraduate,Yes,No,68,48,77,54,64.33,Average,Pass
4,S0005,14,Male,10,5.0,80,High School,Yes,No,41,46,36,68,41.00,Poor,Fail
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,S4996,17,Male,11,4.0,50,Graduate,No,No,64,60,70,93,64.67,Average,Pass
4996,S4997,19,Male,10,5.6,90,High School,Yes,No,44,59,43,63,48.67,Poor,Fail
4997,S4998,16,Female,9,2.3,61,Graduate,No,No,95,41,82,62,72.67,Good,Pass
4998,S4999,15,Male,11,2.9,82,Graduate,No,Yes,66,45,61,75,57.33,Average,Pass
4999,S5000,19,Female,10,2.0,97,Postgraduate,No,Yes,69,53,87,77,69.67,Good,Pass